* Sowa-Kif.org
A KIF encoding of John Sowa's upper ontology.
Adapted from http://suo.ieee.org/SUO/ontologies/Sowa.txt
** Definitions
(documentation disjoint "Classes X and Y are disjoint iff they share no instances.")

(forall (?class1 ?class2)
        (<=> (disjoint ?class1 ?class2)
             (and (Class ?class1)
                  (Class ?class2)
                  (not (exists (?x)
		               (and (instance-of ?x ?class1)
			            (instance-of ?x ?class2)))))))
** Axioms expressing the class hierarchy
(subclass-of Independent Entity)
(subclass-of Relative Entity)
(subclass-of Mediating Entity)
(subclass-of Physical Entity)
(subclass-of Abstract Entity)
(subclass-of Continuant Entity)
(subclass-of Occurrent Entity)

(subclass-of Actuality Independent)
(subclass-of Actuality Physical)
(subclass-of Form Independent)
(subclass-of Form Abstract)
(subclass-of Prehension Physical)
(subclass-of Prehension Relative)
(subclass-of Proposition Relative)
(subclass-of Proposition Abstract)
(subclass-of Nexus Physical)
(subclass-of Nexus Mediating)
(subclass-of Intention Abstract)
(subclass-of Intention Mediating)

(subclass-of Object Actuality)
(subclass-of Object Continuant)
(subclass-of Process Actuality)
(subclass-of Process Occurrent)
(subclass-of Schema Form)
(subclass-of Schema Continuant)
(subclass-of Script Form)
(subclass-of Script Occurrent)
(subclass-of Juncture Prehension)
(subclass-of Juncture Continuant)
(subclass-of Participation Prehension)
(subclass-of Participation Occurrent)
(subclass-of Description Proposition)
(subclass-of Description Continuant)
(subclass-of History Proposition)
(subclass-of History Occurrent)
(subclass-of Structure Nexus)
(subclass-of Structure Continuant)
(subclass-of Situation Nexus)
(subclass-of Situation Occurrent)
(subclass-of Reason Intention)
(subclass-of Reason Continuant)
(subclass-of Purpose Intention)
(subclass-of Purpose Occurrent)

** Documentation for these classes
(documentation Entity "The universal class of individuals, which has no differentiae.")
(documentation Absurdity "The absurd class, which inherits all differentiae.")
(documentation Abstract "Pure information as distinguished from any particular encoding of the information.")
(documentation Physical "An entity that has a location in space-time.")
(documentation Actuality "A physical entity (P) whose existence is independent (I) of any other entity.")
(documentation Continuant "A continuant is an entity whose identity continues to be recognizable over time.")
(documentation Description "A proposition (RA) about a continuant (C). A description is a proposition...")
(documentation Form "Abstract Information (A) independent (I) of any encoding or embodiment...")
(documentation History "A proposition (RA) about an occurrent (O). A history is a proposition (RA)...")
(documentation Independent "An entity characterized by some inherent Firstness, independent of any...")
(documentation Intention "Abstraction (A) considered as mediating (M) other entities. Examples of...")
(documentation Juncture "A prehension (RP) considered as a continuant (C) during some time interval...")
(documentation Mediating "An entity characterized by some Thirdness that brings other entities into a...")
(documentation Nexus "A physical entity (P) mediating (M) two or more other entities. Each nexus is a...")
(documentation Object "Actuality (IP) considered as a continuant (C), which retains its identity over...")
(documentation Occurrent "An entity that does not have a stable identity during any interval of time."...)
(documentation Participation "A prehension (RP) considered as an occurrent (O) during the interval of...")
(documentation Process "Actuality (IP) considered as an occurrent (O) during the interval of interest.")
(documentation Prehension "A physcial entity (P) relative (R) to some entity or entities. The has-test...")
(documentation Proposition "An abstraction (A) that relates (R) some entity or entities. In logic, the...")
(documentation Purpose "Intention (MA) that has the form of an occurrent (O). As an example...")
(documentation Reason "Intention (MA) that has the form of an continuant (C). Unlike a simple description...")
(documentation Relative "An entity is in a relationship to some other entity....")
(documentation Schema "A form (IA) that has the structure of a continuant (C). A schema is an abstract...")
(documentation Script "A form (IA) that has the structure of an occurrent (O). A script is an abstract...")
(documentation Situation "A nexus (MP) considered as an occurrent (O). A situation mediates the...")
(documentation Structure "A nexus (MP) considered as a continuant (C). A structure mediates the...")

** General Axioms
*** AXIOM: X is a subclass of Y only if X and Y are classes...
*** AXIOM: Every class is a subclass of itself.
*** AXIOM: There are entities.
*** AXIOM: Everything is either a class or an entity, but not both.
*** AXIOM: Only entities are instances of classes, and only classes have instances.
*** AXIOM: Entity (the class) consists of exactly the entities...
*** AXIOM: Every class is a subclass of Entity.
*** AXIOM: The has-relation holds between entities.
*** AXIOM: Absurdity is a class.
*** AXIOM: Absurdity has no instances.
*** AXIOM: Absurdity is a subclass of every class.
*** AXIOM: Abstract is a class.
*** AXIOM: ?x is abstract iff it has neither a spatial nor temporal location.
*** AXIOM: ?x is physical iff it exists at some location at some time.
*** THEOREM: Abstract and Physical are disjoint.
*** AXIOM: An independent entity need not bear the "has" relation to anything.
*** AXIOM: A continuant is an object that exists (and, hence, retains its identity) over time.
*** AXIOM: If a mediating entity ?m has ?x and ?y, then either ?x has ?y or vice versa.
*** AXIOM: Continuant and Occurrent are disjoint.
*** AXIOM: The temp-part-of relation holds between entities and occurrents.
*** AXIOM: Each temporal part of an occurrent exists at some timepoint.
*** AXIOM: The spatial-part-of relation holds between entities and occurrents.
*** AXIOM: Each spatial part of an occurrent exists at some location.
*** AXIOM: Occurrents have temporal parts.
*** AXIOM: Occurrents have spatial parts.
*** AXIOM: Every relative entity necessarily bears the has-relation to some entity...
*** AXIOM: Independent and Relative are disjoint.
*** AXIOM: Relative and Mediating are disjoint.
*** AXIOM: Independent and Relative are disjoint.

** Supplementary Ontology
